spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB_SNIPPET}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER_SNIPPET}
    password: ${POSTGRES_PASSWORD_SNIPPET}

  asset:
    service:
      url: ${ASSET_SERVICE_URL}


app:
  websocket:
      allowed-origins: "https://printscript.duckdns.org"

#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: false
#    hibernate:
#      ddl-auto: validate